spring:
  datasource:
    url: jdbc:mysql://telecom-eap.mysql.database.azure.com/telecom
    username: telecomadmin@telecom-eap
    password: password12!
    driver-class-name: com.mysql.cj.jdbc.Driver